# -*- mode: ruby -*-
 
Vagrant.configure("2") do |config|

  #  Configure base  
  config.vm.box = 'centos/7'
  config.ssh.forward_agent = true
  

  # Vault Development
  config.vm.define :vault do |vault|
      vault.vm.hostname = "vault"
      vault.vm.network :private_network, :ip => "192.168.77.200"

      # Start of Vault in mode Dev
      vault.vm.provision :shell, path: "./vault/ServerVault.sh"


      vault.vm.provider :virtualbox do |setting|
           setting.memory = 2048
           setting.cpus = 2
      end
   end
end

